# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Melody Yin
tagline:             'life is a playground'
url:                 http://melodyyin.github.io/
paginate:            3
baseurl:             /

# Conversion
#markdown:         redcarpet
highlighter:      pygments

# About/contact
author:
  name:              Melody Yin
  email:             melodyyin18@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jemoji
  - jekyll-paginate
  - jekyll-gist 