# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Melody Yin
tagline:             'life is a playground'
description:         'hi, my name is Melody'
url:                 http://melodyyin.github.io/
paginate:            5

# About/contact
author:
  name:              Melody Yin
  url:               https://about.me/melodyyin
  email:             melodyyin@u.northwestern.edu

# Custom vars
version:             1.0.0
